version: '3.1'

services:
  db:
    image: mysql:8.0.29-debian
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
  test:
    build: ./