name: MySQL ODBC Performance Testing CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_8_0_19:
    runs-on: ubuntu-latest
    outputs:
      runtime: ${{ steps.test1.outputs.x }}
    steps:
    - uses: actions/checkout@v3
    - id: test1
      name: Perfromance Tests mysql-connector-odbc-8.0.19
      run: |
        docker-compose down
        docker-compose build --build-arg odbcdlurl=https://dev.mysql.com/get/Downloads/Connector-ODBC/8.0/mysql-connector-odbc-8.0.19-linux-glibc2.12-x86-64bit.tar.gz
        docker-compose up --abort-on-container-exit
        dlogs=$(docker-compose logs --no-log-prefix --no-color test | tail -1)
        echo "x=$dlogs" >> $GITHUB_OUTPUT
  
  test_8_0_32:
      runs-on: ubuntu-latest
      outputs:
        runtime: ${{ steps.test1.outputs.x }}
      steps:
      - uses: actions/checkout@v3
      - id: test1
        name: Perfromance Tests mysql-connector-odbc-8.0.33
        run: |
          docker-compose down
          docker-compose build --build-arg odbcdlurl=https://dev.mysql.com/get/Downloads/Connector-ODBC/8.0/mysql-connector-odbc-8.0.33-linux-glibc2.28-x86-64bit.tar.gz
          docker-compose up --abort-on-container-exit
          dlogs=$(docker-compose logs --no-log-prefix --no-color test | tail -1)
          echo "x=$dlogs" >> $GITHUB_OUTPUT
  
  comment_on_pr:
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
      needs: 
        - test_8_0_19
        - test_8_0_32
      steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            mysql-connector-odbc-8.0.19: **${{needs.test_8_0_19.outputs.runtime}}** 
            mysql-connector-odbc-8.0.33: **${{needs.test_8_0_32.outputs.runtime}}**
